config/routes.rb
Rails.application.routes.draw do



  # publicのアクション
  scope module: 'public' do

    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/customers/my_page" => "customers#show", as: "customers"
    get "/customers/edit" => "customers#edit"
    patch "/customers" => "customers#update", as: "customers_update"
    get "/customers/confirm" => "customers#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:edit, :index, :create, :update, :destroy]
  end
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  # adminのアクション
  namespace :admin do
    root to: "homes#top"
    patch "/orders/:id/status" => "orders#status_update", as: "status" # 注文ステータスupdate
    patch "/orders/:id/making_status" => "orders#making_status_update", as: "making_status" # 製作ステータスupdate
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :genres, only: [:edit, :index, :create, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
  # 小計を求めるメソッド

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def full_name
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  #画像を使うための記述
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  def with_tax_price
    (price * 1.1).floor
  end
  # 消費税を求めるメソッド
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum making_status: { not_produced: 0, waiting_for_deposit: 1, production: 2, complete: 3 }

end

app/controllers/admin/customers_controller.rb
class Admin::CustomersController < ApplicationController
  before_action :authenticate_admin!

  def index
    @customers = Customer.page(params[:page])
    # もともとCustomer.all
  end

  def show
    @customer = Customer.find(params[:id])
  end

  def edit
    @customer = Customer.find(params[:id])
  end

  def update
    @customer = Customer.find(params[:id])
    if @customer.update(customer_params)
      redirect_to admin_customer_path
    else
      render :edit
    end
  end

  private
  def customer_params
    params.require(:customer).permit(:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :email, :is_deleted)
  end

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.page(params[:page])
    # もともとGenre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])
    # もともとOrder.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.all
      render :index
    end
  end

  def index
    @items = Item.page(params[:page])
    # もともとItem.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  def item_params
      params.require(:item).permit(:name, :introduction, :price, :image, :genre_id, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @subtotal = 0
    @total_price = 0
    @shipping_cost = 800

  end

  def status_update
    # 注文ステータスのupdate
    @order = Order.find(params[:id])
    @order.update(order_params)
    # 製作ステータスの自動更新
    if params[:order][:status] == "payment_confirmation"
      @order.order_details.update_all(making_status: 1)
      # update_allにすることで注文商品の製作ステータスが更新される
    end
    redirect_to admin_order_path(@order)
  end

  def making_status_update
    # 製作ステータスのupdate
    @order_detail = OrderDetail.find(params[:id])
    @order = @order_detail.order
    @one_order = @order.order_details

    if @order_detail.update(order_detail_params)
    # 注文ステータスの自動更新
      if params[:order_detail][:making_status] == "production"
        @order_detail.order.update(status: 2)
      end

      if @one_order.count == @one_order.where(making_status: "complete").count
        # １件に紐づいたorderのorder_detailsの数 == 左辺のorder_detailsのmaking_statusがcompleteになっている数
        @order_detail.order.update(status: 3)
      end
      redirect_to admin_order_path(@order_detail.order_id)
    end
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:making_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # ログインしていないときはログイン後のページにはすべていけない
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :encrypted_password])
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/customers/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        <%= @customer.last_name %> <%= @customer.first_name %>さんの会員情報編集
      </h4>
    </div>
  </div>
  <%= form_with model: @customer, url: admin_customer_path, method: :patch do |f| %>
    <div class="row my-3">
      <table class="table  table-borderless">
        <tbody>

          <tr>
            <th>会員ID</th>
            <td><%= @customer.id %></td>
          </tr>
          <tr>
            <th>氏名</th>
            <td>
              <%= f.text_field :last_name %>
              <%= f.text_field :first_name %>
            </td>
          </tr>
          <tr>
            <th>フリガナ</th>
            <td>
              <%= f.text_field :last_name_kana %>
              <%= f.text_field :first_name_kana %>
            </td>
          </tr>
          <tr>
            <th>郵便番号</th>
            <td><%= f.text_field :postal_code %></td>
          </tr>
          <tr>
            <th>住所</th>
            <td><%= f.text_field :address %></td>
          </tr>
          <tr>
            <th>電話番号</th>
            <td><%= f.text_field :telephone_number %></td>
          </tr>
          <tr>
            <th>メールアドレス</th>
            <td><%= f.email_field :email %></td>
          </tr>
          <tr>
            <th>会員ステータス</th>
            <td>
              <%= f.radio_button :is_deleted, false %>有効
              <%= f.radio_button :is_deleted, true %>退会
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="row my-3">
      <div class="col-md-10 text-center">
        <%= f.submit '変更を保存', class:"btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/customers/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        会員一覧
      </h4>
    </div>
  </div>
  <div class="row my-3">
    <div class="col-md-12 text-center">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>会員ID</th>
            <th>氏名</th>
            <th>メールアドレス</th>
            <th>ステータス</th>
          </tr>
        </thead>

        <tbody class="col-md-auto">
          <% @customers.each do |customer| %>
          <tr>
            <td><%= customer.id %></td>
            <td><%= link_to customer.last_name + customer.first_name, admin_customer_path(customer.id) %></td>
            <td><%= customer.email %></td>
            <td>
              <% if customer.is_deleted == true %>
              退会
              <% else customer.is_deleted == false %>
              <div class="text-success font-weight-bold">
                有効
              </div>
              <% end %>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row my-2">
    <div class="col-md-12 text-center">
      <%= paginate @customers %>
    </div>
  </div>
</div>

app/views/admin/customers/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4><%= @customer.last_name %> <%= @customer.first_name %>さんの会員詳細</h4>
    </div>
  </div>
  <div class="row my-3">
    <table class="table table-borderless">
      <tbody>
        <tr>
          <th>会員ID</th>
          <td><%= @customer.id %></td>
        </tr>
        <tr>
          <th>氏名</th>
          <td><%= @customer.last_name %> <%= @customer.first_name %></td>
        </tr>
        <tr>
          <th>フリガナ</th>
          <td><%= @customer.last_name_kana %> <%=  @customer.first_name_kana %></td>
        </tr>
        <tr>
          <th>郵便番号</th>
          <td><%= @customer.postal_code %></td>
        </tr>
        <tr>
          <th>住所</th>
          <td><%= @customer.address %></td>
        </tr>
        <tr>
          <th>電話番号</th>
          <td><%= @customer.telephone_number %></td>
        </tr>
        <tr>
          <th>メールアドレス</th>
          <td><%= @customer.email %></td>
        </tr>
        <tr>
          <th>会員ステータス</th>
          <td>
            <% if @customer.is_deleted == true %>
            退会
            <% else @customer.is_deleted == false %>
            <div class="text-success font-weight-bold">
              有効
            </div>
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  </div>
  <div class="row my-2">
    <div class="col-md-6 text-right">
      <%= link_to "編集する", edit_admin_customer_path(@customer.id), class:"btn btn-success" %>
    </div>
    <div class="col-md-6 text-left">
      <%= link_to "注文履歴一覧を見る", admin_root_path, class:"btn btn-primary" %>
    </div>
  </div>
</div>