config/routes.rb
Rails.application.routes.draw do



  # publicのアクション
  scope module: 'public' do

    root to: "homes#top"
    get "/about" => "homes#about", as: "about"
    get "/customers/my_page" => "customers#show", as: "customers"
    get "/customers/edit" => "customers#edit"
    patch "/customers" => "customers#update", as: "customers_update"
    get "/customers/confirm" => "customers#confirm"
    patch "/customers/withdraw" => "customers#withdraw"
    delete "/cart_items/destroy_all" => "cart_items#destroy_all"
    post "/orders/confirm" => "orders#confirm"
    get "/orders/complete" => "orders#complete"
    resources :items, only: [:show, :index]
    resources :cart_items, only: [:create, :index, :update, :destroy]
    resources :orders, only: [:new, :index, :show, :create]
    resources :addresses, only: [:edit, :index, :create, :update, :destroy]
  end
  devise_for :customers,skip: [:passwords], controllers: {
    registrations: "public/registrations",
    sessions: 'public/sessions'
  }

  devise_for :admin, skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
  }
  # adminのアクション
  namespace :admin do
    root to: "homes#top"
    patch "/orders/:id/status" => "orders#status_update", as: "status" # 注文ステータスupdate
    patch "/orders/:id/making_status" => "orders#making_status_update", as: "making_status" # 製作ステータスupdate
    resources :items, only: [:new, :index, :create, :show, :edit, :update]
    resources :genres, only: [:edit, :index, :create, :update]
    resources :customers, only: [:show, :index, :edit, :update]
    resources :orders, only: [:show, :update]
    resources :order_details, only: [:update]
  end
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :customer

  def address_display
    '〒' + postal_code + ' ' + address + ' ' + name
  end
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :customer
  belongs_to :item
  def subtotal
    item.with_tax_price * amount
  end
  # 小計を求めるメソッド

end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :cart_items
  has_many :orders
  has_many :addresses

  def full_name
    last_name + first_name
  end

end

app/models/genre.rb
class Genre < ApplicationRecord
  has_many :items
end

app/models/item.rb
class Item < ApplicationRecord
  has_one_attached :image
  #画像を使うための記述
  belongs_to :genre
  has_many :order_details
  has_many :cart_items
  def with_tax_price
    (price * 1.1).floor
  end
  # 消費税を求めるメソッド
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :customer
  has_many :order_details
  enum payment_method: { credit_card: 0, transfer: 1 }
  enum status: { waiting_for_deposit: 0, payment_confirmation: 1, production: 2, ready_to_ship: 3, sent: 4 }
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
  belongs_to :item
  belongs_to :order
  enum making_status: { not_produced: 0, waiting_for_deposit: 1, production: 2, complete: 3 }

end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
  before_action :authenticate_admin!

  def index
    @genres = Genre.page(params[:page])
    # もともとGenre.all
    @genre = Genre.new
  end

  def create
    @genre = Genre.new(genre_params)
    if @genre.save
      redirect_to admin_genres_path
    else
      @genres = Genre.all
      render :index
    end
  end

  def edit
    @genre = Genre.find(params[:id])
  end

  def update
    @genre = Genre.find(params[:id])
    if @genre.update(genre_params)
      redirect_to admin_genres_path
    else
      render :edit
    end
  end

  private
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
  before_action :authenticate_admin!
  def top
    @orders = Order.page(params[:page])
    # もともとOrder.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :authenticate_admin!
  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to admin_item_path(@item.id)
    else
      @items = Item.all
      render :index
    end
  end

  def index
    @items = Item.page(params[:page])
    # もともとItem.all
    @item = Item.new
  end

  def show
    @item = Item.find(params[:id])
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    if @item.update(item_params)
      redirect_to admin_item_path(@item.id)
    else
      render :edit
    end
  end

  private
  def item_params
      params.require(:item).permit(:name, :introduction, :price, :image, :genre_id, :is_active)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
  before_action :authenticate_admin!
  def show
    @order = Order.find(params[:id])
    @order_details = @order.order_details
    @subtotal = 0
    @total_price = 0
    @shipping_cost = 800

  end

  def status_update
    # 注文ステータスのupdate
    @order = Order.find(params[:id])
    @order.update(order_params)
    # 製作ステータスの自動更新
    if params[:order][:status] == "payment_confirmation"
      @order.order_details.update_all(making_status: 1)
      # update_allにすることで注文商品の製作ステータスが更新される
    end
    redirect_to admin_order_path(@order)
  end

  def making_status_update
    # 製作ステータスのupdate
    @order_detail = OrderDetail.find(params[:id])
    @order = @order_detail.order
    @one_order = @order.order_details

    if @order_detail.update(order_detail_params)
    # 注文ステータスの自動更新
      if params[:order_detail][:making_status] == "production"
        @order_detail.order.update(status: 2)
      end

      if @one_order.count == @one_order.where(making_status: "complete").count
        # １件に紐づいたorderのorder_detailsの数 == 左辺のorder_detailsのmaking_statusがcompleteになっている数
        @order_detail.order.update(status: 3)
      end
      redirect_to admin_order_path(@order_detail.order_id)
    end
  end

  private
  def order_params
    params.require(:order).permit(:status)
  end

  def order_detail_params
    params.require(:order_detail).permit(:making_status)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  # ログインしていないときはログイン後のページにはすべていけない
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number, :encrypted_password])
  end
  
  
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_details_helper.rb
module Admin::OrdersDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/admin/genres/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        ジャンル編集
      </h4>
    </div>
  </div>
  <%= form_with model: @genre, url: admin_genre_path, method: :patch do |f| %>
    <div class="row my-5">
      <div class="col-md-auto">
        ジャンル名
        <%= f.text_field :name %>
        <%= f.submit '変更を保存', class:'btn btn-success' %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/genres/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        ジャンル一覧・追加
      </h4>
    </div>
  </div>
  <%= form_with model: @genre, url: admin_genres_path, method: :post do |f| %>
    <div class="row my-3">
      <div class="col-md-4 font-weight-bold">
        ジャンル名
      </div>
      <div class="col-md-5 text-left">
        <%= f.text_field :name %>
      </div>
      <div class="col-md-3 text-left">
        <%= f.submit '新規登録', class:"btn btn-success" %>
      </div>
    </div>
  <% end %>
  <div class="row my-3">
    <div class="col-md-7">
      <table class="table">
        <thead class="bg-light">
          <tr>
            <th>ジャンル</th>
            <th></th>
          </tr>
        </thead>
        <tbody class="table">
        <% @genres.each do |genre| %>
          <tr>
            <th class="row">
              <tb class="col-md-5">
                <%= genre.name %>
              </tb>
              <tb class="col-md-7 text-right">
                <%= link_to "編集する", edit_admin_genre_path(genre.id), class:"btn btn-success" %>
              </tb>
            </th>
          </tr>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row my-2">
    <div class="col-md-12 text-center">
      <%= paginate @genres %>
    </div>
  </div>
</div>

app/views/admin/items/edit.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        商品編集
      </h4>
    </div>
  </div>
  <%= form_with model: @item, url: admin_item_path(@item.id), method: :patch do |f| %>
    <div class="row my-3">
      <div class="col-md-12 text-center">
        <table class="table table-borderless">
          <tdody>
            <tr>
              <th>商品画像</th>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <th>商品名</th>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --" %></td>
              <!-- f.collection_select :保存先のカラム名, 選択肢に使うオブジェクト, :一つ目の引数に渡す値, :選択肢に使うカラム名, include_blank: "選択して下さい" -->
            </tr>
            <tr>
              <th>税抜価格</th>
              <td><%= f.text_field :price %>円</td>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <td>
                <%= f.radio_button :is_active, true %>販売中
                <%= f.radio_button :is_active, false %>販売停止中
                <!--<= f.radio_button :保存先のカラム名, "送る値" %>-->
                <!--is_activeの送れる値はtrue,falseの二つのみ-->
              </td>
            </tr>
          </tdody>
        </table>
      </div>
    </div>
    <div class="row my-2">
      <div class="col-md-12 text-center">
        <%= f.submit "変更を保存", class:"btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/index.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        商品一覧
      </h4>
    </div>
    <div class="col text-right">
      <%= link_to "商品新規登録", new_admin_item_path, class:"btn btn-secondary btn-lg" %>
    </div>
  </div>
  <div class="row my-4">
    <table class="table">
      <thead class="bg-light">
        <tr>
          <th>商品ID</th>
          <th>商品名</th>
          <th>税抜価格</th>
          <th>ジャンル</th>
          <th>ステータス</th>
        </tr>
      </thead>
      <tbody>
        <% @items.each do |item| %>
        <tr>
          <td><%= item.id %></td>
          <td>
            <div class="link-dark"><%= link_to item.name, admin_item_path(item.id) %></div>
          </td>
          <td><%= item.price %></td>
          <td><%= item.genre.name %></td>
          <td>
            <% if item.is_active == true %>
            <div class="text-success">販売中</div>
            <% else item.is_active == false %>
            <div class="text-black-50">販売停止中</div>
            <% end %>
          </td>
        </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="row">
    <div class="col-md-12 text-center">
      <%= paginate @items %>
    </div>
  </div>
</div>

app/views/admin/items/new.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        商品新規登録
      </h4>
    </div>
  </div>
  <%= form_with model: @item, url: admin_items_path do |f| %>
    <div class="row my-4">
      <div class="col-md-12 text-center">
        <table class="table table-borderless">
          <tbody>
            <tr>
              <th>商品画像</th>
              <td><%= f.file_field :image, accept: "image/*" %></td>
            </tr>
            <tr>
              <th>商品名</th>
              <td><%= f.text_field :name %></td>
            </tr>
            <tr>
              <th>商品説明</th>
              <td><%= f.text_area :introduction %></td>
            </tr>
            <tr>
              <th>ジャンル</th>
              <td><%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: "-- 選択してください --" %></td>
              <!-- f.collection_select :保存先のカラム名, 選択肢に使うオブジェクト, :一つ目の引数に渡す値, :選択肢に使うカラム名, include_blank: "選択して下さい" -->
            </tr>
            <tr>
              <th>税抜価格</th>
              <td><%= f.text_field :price %>円</td>
            </tr>
            <tr>
              <th>販売ステータス</th>
              <td>
                <%= f.radio_button :is_active, true %>販売中
                <%= f.radio_button :is_active, false %>販売停止中
                <!--<= f.radio_button :保存先のカラム名, "送る値" %>-->
                <!--is_activeの送れる値はtrue,falseの二つのみ-->
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    <div class="row my-2">
      <div class="col-md-12 text-center">
        <%= f.submit '新規登録', class:"btn btn-success" %>
      </div>
    </div>
  <% end %>
</div>

app/views/admin/items/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        商品詳細
      </h4>
    </div>
  </div>
  <div class="row my-5">
    <div class="col-md-4">
      <% if @item.image.attached? %>
      <!--画像は存在しないものとして保存が実行されるif文-->
      <%= image_tag @item.image, size: "200x200" %>
      <% end %>
    </div>
    <div class="col-md-6">
      <table class="table table-borderless">
        <tbody>
          <tr>
            <th>商品名</th>
            <td><%= @item.name %></td>
          </tr>
          <tr>
            <th>商品説明</th>
            <td><%= @item.introduction %></td>
          </tr>
          <tr>
            <th>ジャンル</th>
            <td><%= @item.genre.name %></td>
          </tr>
          <tr>
            <th>税込価格(税抜価格)</th>
            <td><%= @item.with_tax_price %> (<%= @item.price %>)円</td>
          </tr>
          <tr>
            <th>販売ステータス</th>
            <td class="text-success font-weight-bold">
            <% if @item.is_active == true %>
              販売中
            <% else @item.is_active == false %>
              販売停止中
            <% end %>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="field row mx-auto">
      <%= link_to "編集する", edit_admin_item_path(@item.id), class:"btn btn-success" %>
    </div>
  </div>
</div>

app/views/admin/orders/show.html.erb
<div class="container my-5">
  <div class="row">
    <div class="col-md-auto bg-light">
      <h4 class="font-weight-bold">
        注文履歴詳細
      </h4>
    </div>
  </div>
  <div class="row my-3">
    <table class="table table-borderless">
      <thead>
        <tr>
          <th>購入者</th>
          <td><%= @order.customer.last_name %> <%= @order.customer.first_name %></td>
        </tr>
        <tr>
          <th>注文日</th>
          <td><%= @order.created_at.strftime("%Y/ %m/ %d") %></td>
        </tr>
        <tr>
          <th>配送先</th>
          <td>
            〒<%= @order.postal_code %> <%= @order.address %>
            <%= @order.name %>
          </td>
        </tr>
        <tr>
          <th>支払方法</th>
          <td><%= @order.payment_method_i18n %></td>
        </tr>
        <tr>
          <th>注文ステータス</th>
          <td>
            <%= form_with model: @order, url: admin_status_path(@order), method: :patch do |f| %>
              <%= f.select :status,Order.statuses_i18n.invert %>
              <%= f.submit "更新", class:"btn btn-success" %>
            <% end %>
          </td>
        </tr>
      </thead>
    </table>
  </div>
  <div class="row my-3">
    <div class="col-md-9">
      <table class="table table-bordered">
        <thead class="bg-light">
          <tr>
            <th>商品名</th>
            <th>単価(税込)</th>
            <th>数量</th>
            <th>小計</th>
            <th>製作ステータス</th>
          </tr>
        </thead>
        <tbody>
          <% @order_details.each do |order_detail| %>
            <tr>
              <td><%= order_detail.item.name %></td>
              <td><%= order_detail.price %></td>
              <td><%= order_detail.amount %></td>
              <td><%= @subtotal = order_detail.price * order_detail.amount %></td>
                  <% @total_price += @subtotal %>
              <%= form_with model: order_detail, url: admin_making_status_path(order_detail), method: :patch do |f| %>
                <td>
                  <%= f.select :making_status, OrderDetail.making_statuses_i18n.invert %>
                  <%= f.submit "更新", class:"btn btn-success" %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <div class="col-md-3-auto mt-5">
      <table>
        <thead>
          <tr>
            <th>商品合計</th>
            <td class="text-right"><%= @total_price %>円</td>
          </tr>
          <tr>
            <th>配送料</th>
            <td class="text-right"><%= @shipping_cost %>円</td>
          </tr>
          <tr>
            <th>請求金額合計</th>
            <td class="text-right"><%= @total_price += @shipping_cost %>円</td>
          </tr>
        </thead>
      </table>
    </div>
  </div>
</div>